-- MySQL Script generated by MySQL Workbench
-- Tue May 19 09:32:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `cellphone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(10,2) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `ncm` VARCHAR(8) NOT NULL,
  `production_time` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `pis` VARCHAR(15) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `status` ENUM('ATIVO', 'DESLIGADO', 'FERIAS', 'AFASTADO') NOT NULL,
  `birth_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `pis_UNIQUE` (`pis` ASC) VISIBLE,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `start_date` DATE NULL,
  `expected_delivery_date` DATE NULL,
  `status` ENUM('EM_ESPERA', 'EM_PRODUCAO', 'FINALIZADO') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_client_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_orders_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`daily_production`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`daily_production` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orders_id` INT NOT NULL,
  `current_date` DATE NOT NULL,
  `expected_production` INT NOT NULL,
  `actual_production` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_daily_production_orders1_idx` (`orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_daily_production_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `mydb`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`daily_production_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`daily_production_employees` (
  `daily_production_id` INT NOT NULL,
  `employees_id` INT NOT NULL,
  PRIMARY KEY (`daily_production_id`, `employees_id`),
  INDEX `fk_daily_production_employees_employees1_idx` (`employees_id` ASC) VISIBLE,
  CONSTRAINT `fk_daily_production_employees_daily_production1`
    FOREIGN KEY (`daily_production_id`)
    REFERENCES `mydb`.`daily_production` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_daily_production_employees_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `mydb`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`financial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`financial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `daily_production_id` INT NOT NULL,
  `quantity_delivered` INT NOT NULL,
  `total_billed` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_financial_daily_production1_idx` (`daily_production_id` ASC) VISIBLE,
  CONSTRAINT `fk_financial_daily_production1`
    FOREIGN KEY (`daily_production_id`)
    REFERENCES `mydb`.`daily_production` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`machine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`machine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `serial_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`machine_maintenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`machine_maintenance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `machine_id` INT NOT NULL,
  `maintenense_date` DATE NOT NULL,
  `mechanic_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_machine_maintenence_machine1_idx` (`machine_id` ASC) VISIBLE,
  CONSTRAINT `fk_machine_maintenence_machine1`
    FOREIGN KEY (`machine_id`)
    REFERENCES `mydb`.`machine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
